added comments
HeavyTechRuby/history pull request #65
Opened 2024-06-01 08:13 UTC by o-200

#56 
Добавил возможность добавлять "комментарии" к "объектам". Создал сущность по скаффолду, добавил базовые валидации, поменял роуты и тесты.

2024-06-01 16:08 UTC, realvint commented
Пустые тесты это не хорошо. Как и пустые хелперы

2024-06-01 16:19 UTC, realvint commented
А где стили то?)

2024-06-02 19:36 UTC, realvint commented
у тебя внутри `ul` каждый `li`  в диве) нинадо так. `li` должен быть корневой с айдишником сразу

2024-06-02 19:37 UTC, realvint commented
Вместо each по коллекциям можно сразу рендерить коллекцию, рельсы так умеют, если партиал в правильном месте лежит

2024-06-03 05:32 UTC, sergio-fry requested changes
Не хватает feature-тестов, сценарий был указан в issue

2024-06-03 05:32 UTC, sergio-fry commented on app/views/comments/_form.html.erb
> +                <%= form.submit "Create Comment", class: 'btn btn-primary' %>
i18n

2024-06-03 05:32 UTC, sergio-fry commented on app/views/comments/_form.html.erb
> +                    <%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:
i18n

2024-06-03 05:32 UTC, sergio-fry commented on db/schema.rb
> +  create_table "discussions", force: :cascade do |t|
А зачем нужная эта сущность?

2024-06-03 05:41 UTC, o-200 commented on db/schema.rb
> +  create_table "discussions", force: :cascade do |t|
> А зачем нужная эта сущность?

она ошибочная. Я думал сначала вместо комментариев создать таблицу с этим названием, но по смыслу не подходит и может в будущем запутывать. 

Удалю её.

2024-06-04 05:18 UTC, sergio-fry approved these changes
Кажется, мы уже близки, но есть несколько замечаний.

2024-06-04 05:18 UTC, sergio-fry commented on features/F03-history-comments.feature
> +		Дано история с адресом "Москва, Ленина 12" и телом "Я тут родился!!" вместе с комментарием "хороший город"
У нас есть блоки: Дано, Когда, Тогда. Принято, чтобы начало блока начиналось с ключевого слова, а дальше уже каждая строка в этом же блоке начиналась с "И". То есть, лучше,

Дано я гость
И история с адресом...

2024-06-04 05:18 UTC, sergio-fry commented on features/F03-history-comments.feature
> +		Дано история с адресом "Москва, Ленина 12" и телом "Я тут родился!!" вместе с комментарием "хороший город"
Крупные шаги сложнее переиспользовать. Тут я бы посоветовал выделить "вместе с комментарием "хороший город"" - в отдельный. Это даст нам возможность добавлять несколько комментариев к одной истории тем же step.

2024-06-04 05:18 UTC, sergio-fry commented on app/views/comments/index.html.erb
> +<h1>Comments</h1>
i18n нужно посмотреть везде, а не только, где я подсказал

2024-06-04 05:42 UTC, sergio-fry commented
@o-200 накопились конфликты, сорри

2024-06-04 08:40 UTC, o-200 commented
добавил i18n gem чтобы переводились все возможные валидации/ошибки.

2024-06-04 09:24 UTC, sergio-fry requested changes

2024-06-04 09:24 UTC, sergio-fry commented on app/controllers/comments_controller.rb
> +        format.html { redirect_to @story, notice: "Comment was successfully updated." }
i18n

2024-06-04 09:55 UTC, realvint commented
@o-200 добавь перевод атрибутов, это сразу переведёт лэйблы и атрибуты в сообщениях об ошибках

2024-06-05 12:42 UTC, o-200 commented
@sergio-fry нужно ревью. Конфликты буду решать в последний момент когда одобришь работу

2024-06-05 14:57 UTC, sergio-fry commented on app/views/comments/edit.html.erb
> +  <%= link_to "Show this comment", @comment %> |
i18n

2024-06-06 07:24 UTC, sergio-fry approved these changes

2024-06-06 07:24 UTC, merged