Add deploy job
HeavyTechRuby/history pull request #79
Opened 2024-06-07 08:38 UTC by petrolax

closes #68 

Необходимо добавить секреты DOKKU_GIT_REMOTE_URL и DOKKU_SSH_PRIVATE_KEY для коннекта к нашему dokku

2024-06-11 05:12 UTC, sergio-fry requested changes
Есть небольшой коммент. ENV добавил, если что

2024-06-11 05:12 UTC, sergio-fry commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/a3a5daaab0db5b759cc3/maintainability)](https://codeclimate.com/github/HeavyTechRuby/history/maintainability)
а это почему меняем? кажется, не связанно с задачей

2024-06-11 05:16 UTC, petrolax commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/a3a5daaab0db5b759cc3/maintainability)](https://codeclimate.com/github/HeavyTechRuby/history/maintainability)
Да, не связано с задачей, правка минимальная и не значительная, но обратил внимание что если прописать через api, то качество пикчи бейджа получше. Могу убрать, если критично)

2024-06-11 05:18 UTC, sergio-fry commented on README.md
> +[![Maintainability](https://api.codeclimate.com/v1/badges/a3a5daaab0db5b759cc3/maintainability)](https://codeclimate.com/github/HeavyTechRuby/history/maintainability)
давай учиться делать правильно, создай отдельный PR для этого

2024-07-26 11:09 UTC, sergio-fry approved these changes

2024-07-26 11:09 UTC, merged