Add Docker
HeavyTechRuby/history pull request #83
Opened 2024-06-11 21:36 UTC by sk8higher

Closes #80

2024-06-11 21:45 UTC, AlexNimoy commented on config/database.yml
> +  password: <%= ENV["POSTGRES_PASSWORD"] %>
Эти параметры можно задать через DATABASE_URL
`<database_type>://<username>:<password>@<host>:<port>/<database_name>`

2024-06-11 21:45 UTC, AlexNimoy commented on README.md
> +echo "DATABASE_URL=postgresql://postgres@0.0.0.0:5432/history_test
Имя базы данных можно не указывать если оно не задано подхватится из config/database.yml
Пароль тоже можно указать в DATABASE_URL
<database_type>://<username>:<password>@<host>:<port>/<database_name>

2024-06-11 22:00 UTC, AlexNimoy commented on docker-compose.yml
> +      - '5432:5432'
Порты точно надо прокидывать наружу?
Может быть конфликт если установлен postgres локально.
И по идее контейнер postgres:5432 доступен внутри сети докера

2024-06-11 22:36 UTC, sk8higher commented on docker-compose.yml
> +      - '5432:5432'
проверила с локально запущенным, конфликтует

2024-06-12 09:11 UTC, sergio-fry requested changes

2024-06-12 09:11 UTC, sergio-fry commented on Dockerfile.production
Dokku собирает образ именно по этому файлу. Переименование сломает эту логику.

2024-06-12 09:11 UTC, sergio-fry commented on README.md
> -* rails db:create db:migrate
А явного запуска миграций сработает? Кажется, первый раз, все равно, нужно запускать.

2024-06-12 09:48 UTC, AlexNimoy commented on README.md
> -* rails db:create db:migrate
Для подготовки окружения на сколько я понял есть специальная опция:

```yaml
provision:
  - dip compose down --volumes
  - dip clean_cache
  - dip compose up -d pg redis
  - dip bash -c ./bin/setup
 ```

2024-06-14 14:31 UTC, sk8higher commented
Без `POSTGRES_HOST_AUTH_METHOD: "trust"` не хочет работать база, но это не хорошо использовать. Оставить или добавить в env файлы `POSTGRES_PASSWORD` переменную для root-пароля?

2024-06-14 15:22 UTC, sergio-fry approved these changes

2024-06-14 15:23 UTC, merged